# -> SYSTEM
server:
  port: 8080
  error.whitelabel.enabled: false

logging.level:
  org.springframework.jdbc.core.JdbcTemplate: debug

# -> HIBERNATE
#spring.jpa.hibernate.ddl-auto: update

# -> DB INIT
#spring.sql.init:
#  mode: always
#  data-locations: classpath:db/uidb-h2.sql

# -> MYSQL
#spring.datasource:
#  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/uidb?serverTimezone=UTC
#  url: jdbc:mysql://localhost:3306/uidb?serverTimezone=UTC
#  driverClassName: com.mysql.cj.jdbc.Driver
#  username: root
#  password:

# -> H2
spring.datasource:
  url: jdbc:h2:mem:db
  driverClassName: org.h2.Driver
  username: sa
  password:

# -> H2 CONSOLE
spring.h2.console:
  enabled: true
  path: /h2-console

# -> LIQUIBASE
spring.liquibase:
  change-log: classpath:db/changelog/master.xml
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}

# -> LDAP
#spring.ldap:
#  password: ${spring.datasource.password}
